import { defaultRows } from "../src/lib/permissions/defaults";

/**
 * Prints the default-grant INSERT so the migration is generated from the same
 * source the tests assert, rather than typed by hand. Regenerate; do not edit
 * the migration in place.
 */
const values = defaultRows()
  .map((row) => `  ('${row.role}', '${row.action}', ${row.granted}, NOW())`)
  .join(",\n");

console.log(`-- Phase 48 default grants. Generated by scripts/print-permission-seed.ts
-- from src/lib/permissions/defaults.ts. Do not hand-edit: regenerate.
INSERT INTO "PermissionGrant" ("role", "action", "granted", "updatedAt") VALUES
${values}
ON CONFLICT ("role", "action") DO NOTHING;`)
