/**
 * Preview → local env helpers. Never log secret values — only key names and
 * Neon endpoint prefixes (ep-…). Production is ep-polished-wildflower;
 * development is ep-mute-frog (see context/current-feature.md).
 */

export const PRODUCTION_NEON_ENDPOINTS = ["ep-polished-wildflower"];
export const DEVELOPMENT_NEON_ENDPOINTS = ["ep-mute-frog"];
export const DEV_R2_BUCKET = "loving-hands-portal-dev";
export const PRODUCTION_R2_BUCKET = "loving-hands-portal";

const DROP_KEYS = new Set([
  "NEON_LOCAL",
  "NEON_LOCAL_PROXY_PORT",
  "VERCEL_URL",
  "VERCEL_BRANCH_URL",
  "VERCEL_PROJECT_PRODUCTION_URL",
]);

export function parseEnv(text) {
  /** @type {Record<string, string>} */
  const out = {};
  for (const line of text.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq <= 0) continue;
    const key = trimmed.slice(0, eq).trim();
    let value = trimmed.slice(eq + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    value = value.replace(/\\n/g, "\n").replace(/\\"/g, '"');
    out[key] = value;
  }
  return out;
}

export function serializeEnv(vars) {
  const lines = [
    "# Generated by scripts/dev/wire-preview-env.sh from Vercel Preview.",
    "# Do not commit. Values are secrets. DATABASE_URL/DIRECT_URL appear once.",
    "",
  ];
  for (const [key, value] of Object.entries(vars)) {
    const escaped = String(value)
      .replace(/\\/g, "\\\\")
      .replace(/\n/g, "\\n")
      .replace(/"/g, '\\"');
    lines.push(`${key}="${escaped}"`);
  }
  lines.push("");
  return lines.join("\n");
}

export function neonEndpoint(url) {
  if (!url) return null;
  try {
    const normalised = url.replace(/^postgres(ql)?:/i, "http:");
    const host = new URL(normalised).hostname;
    const match = host.match(/^(ep-[a-z0-9-]+)/i);
    return { host, endpoint: match ? match[1].toLowerCase() : host.toLowerCase() };
  } catch {
    return null;
  }
}

function matchesEndpoint(info, markers) {
  if (!info) return false;
  return markers.some(
    (marker) =>
      info.endpoint === marker || info.endpoint.startsWith(`${marker}-`),
  );
}

export function isProductionNeon(url) {
  return matchesEndpoint(neonEndpoint(url), PRODUCTION_NEON_ENDPOINTS);
}

export function isDevelopmentNeon(url) {
  return matchesEndpoint(neonEndpoint(url), DEVELOPMENT_NEON_ENDPOINTS);
}

/**
 * @param {Record<string, string>} preview
 * @param {Record<string, string> | null} production
 */
export function assertSafeForLocalDev(preview, production) {
  const databaseUrl = preview.DATABASE_URL ?? "";
  const directUrl = preview.DIRECT_URL ?? "";
  if (!databaseUrl || !directUrl) {
    throw new Error(
      "Preview env is missing DATABASE_URL or DIRECT_URL. Refusing to write .env.local.",
    );
  }

  const previewDb = neonEndpoint(databaseUrl);
  const previewDirect = neonEndpoint(directUrl);
  const productionDb = production ? neonEndpoint(production.DATABASE_URL ?? "") : null;

  if (!previewDb) {
    throw new Error("Preview DATABASE_URL host could not be parsed. Refusing.");
  }

  if (isProductionNeon(databaseUrl) || isProductionNeon(directUrl)) {
    throw new Error(
      `Preview DATABASE_URL/DIRECT_URL points at production Neon (${previewDb.endpoint}). ` +
        "Refusing to write .env.local and will not migrate or seed.",
    );
  }

  if (
    productionDb &&
    (previewDb.host === productionDb.host ||
      (previewDirect && previewDirect.host === productionDb.host))
  ) {
    throw new Error(
      "Preview Neon host matches production. Refusing to write .env.local.",
    );
  }

  return {
    databaseEndpoint: previewDb.endpoint,
    directEndpoint: previewDirect?.endpoint ?? null,
    isKnownDevelopment: isDevelopmentNeon(databaseUrl),
  };
}

export function applyLocalOverrides(preview) {
  /** @type {Record<string, string>} */
  const next = {};
  for (const [key, value] of Object.entries(preview)) {
    if (DROP_KEYS.has(key)) continue;
    next[key] = value;
  }
  next.APP_URL = "http://localhost:3000";
  next.SHOP_HOST = "";
  next.SHOP_URL = "";
  next.R2_BUCKET = DEV_R2_BUCKET;
  return next;
}

export function requiredKeysFromExample(exampleText) {
  return Object.keys(parseEnv(exampleText)).filter((key) => !DROP_KEYS.has(key));
}

export function missingRequiredKeys(vars, required) {
  return required.filter((key) => {
    if (key === "SHOP_HOST" || key === "SHOP_URL") return false;
    if (key.startsWith("SUPPLIER_")) return false;
    if (key === "AUTO_APPROVE_DOMAIN" || key === "SEED_SUPER_ADMIN_EMAIL") {
      return false;
    }
    const value = vars[key];
    return value === undefined || value === "";
  });
}
